// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ContextMenu: typeof import('./../components/ContextMenu/ContextMenu.vue')['default']
    ContextMenuContent: typeof import('./../components/ContextMenu/ContextMenuContent.vue')['default']
    ContextMenuItem: typeof import('./../components/ContextMenu/ContextMenuItem.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileBase: typeof import('./../components/FileComponents/FileBase.vue')['default']
    FileItem: typeof import('./../components/FileComponents/FileItem.vue')['default']
    Folder: typeof import('./../components/FileComponents/Folder.vue')['default']
    FolderItem: typeof import('./../components/FileComponents/FolderItem.vue')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpBaseline123: typeof import('~icons/ep/baseline123')['default']
    IEpMaterialSymbols10k: typeof import('~icons/ep/material-symbols10k')['default']
    IIcBaseline10k: typeof import('~icons/ic/baseline10k')['default']
    IIcBaseline12: typeof import('~icons/ic/baseline12')['default']
    IIcBaseline123: typeof import('~icons/ic/baseline123')['default']
    IMaterialSymbols10kOutline: typeof import('~icons/material-symbols/10k-outline')['default']
    OnClickOutside: typeof import('@vueuse/components')['OnClickOutside']
    RenameDialog: typeof import('./../components/businessComponents/RenameDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateFileItem: typeof import('./../components/businessComponents/StateFileItem.vue')['default']
    StateFolderItem: typeof import('./../components/businessComponents/StateFolderItem.vue')['default']
    UnknownFile: typeof import('./../components/FileComponents/UnknownFile.vue')['default']
  }
}
